from recipes.almahelpers import fixsyscaltimes # SACM/JAO - Fixes
__rethrow_casa_exceptions = True
context = h_init()
context.set_state('ProjectSummary', 'proposal_code', '2017.1.01355.L')
context.set_state('ProjectSummary', 'piname', 'unknown')
context.set_state('ProjectSummary', 'proposal_title', 'unknown')
context.set_state('ProjectStructure', 'ous_part_id', 'X738487140')
context.set_state('ProjectStructure', 'ous_title', 'Undefined')
context.set_state('ProjectStructure', 'ppr_file', '/opt/dared/opt/c5r1/mnt/dataproc/2017.1.01355.L_2018_01_25T14_45_02.430/SOUS_uid___A001_X1296_X179/GOUS_uid___A001_X1296_X17a/MOUS_uid___A001_X1296_X17b/working/PPR_uid___A001_X1296_X17c.xml')
context.set_state('ProjectStructure', 'ps_entity_id', 'uid://A001/X1220/Xddd')
context.set_state('ProjectStructure', 'recipe_name', 'hifa_calimage')
context.set_state('ProjectStructure', 'ous_entity_id', 'uid://A001/X1220/Xdd9')
context.set_state('ProjectStructure', 'ousstatus_entity_id', 'uid://A001/X1296/X17b')
try:
    hifa_importdata(vis=['uid___A002_Xc889b6_X5cbc'], session=['session_1'])
    fixsyscaltimes(vis = 'uid___A002_Xc889b6_X5cbc.ms')# SACM/JAO - Fixes
    h_save() # SACM/JAO - Finish weblog after fixes
    h_init() # SACM/JAO - Restart weblog after fixes
    hifa_importdata(vis=['uid___A002_Xc889b6_X5cbc'], session=['session_1'])
    hifa_flagdata(pipelinemode="automatic")
    hifa_fluxcalflag(pipelinemode="automatic")
    hif_rawflagchans(pipelinemode="automatic")
    hif_refant(pipelinemode="automatic")
    h_tsyscal(pipelinemode="automatic")
    # hifa_tsysflag(fnm_limit=2.0, flag_fieldshape=True, flag_edgechans=True, tmef1_limit=0.666, normalize_tsys=False, ff_max_limit=5.0, fb_sharps_limit=0.05, tmf1_limit=0.666, ff_refintent='BANDPASS', fnm_byfield=False, flag_toomany=True, fd_max_limit=5.0, fe_edge_limit=3.0, flag_derivative=True, metric_order='nmedian,derivative,edgechans,fieldshape,birdies,toomany', flag_birdies=True, flag_nmedian=True)
    #
    # The Tsys calibration table is analyzed and deviant points are flagged.
    #
    flagdata(vis='uid___A002_Xc889b6_X5cbc.ms.h_tsyscal.s6_1.tsyscal.tbl', mode='summary')
    flagdata(vis='uid___A002_Xc889b6_X5cbc.ms.h_tsyscal.s6_1.tsyscal.tbl', mode='summary')
    flagdata(flagbackup=False, vis='uid___A002_Xc889b6_X5cbc.ms.h_tsyscal.s6_1.tsyscal.tbl', reason='any', mode='list', action='apply', savepars=False, inpfile=["mode='summary' name='before'", "spw='17:0~3;123~127' reason='edges'", "spw='19:0~5;123~127' reason='edges'", "spw='21:0~3;123~127' reason='edges'", "spw='17:0~3;123~127' reason='edges'", "spw='19:0~5;124~127' reason='edges'", "spw='21:0~3;123~127' reason='edges'", "spw='19:0~5;124~127' reason='edges'", "spw='21:0~3;123~127' reason='edges'", "spw='23:0~3;126~127' reason='edges'", "spw='23:0~3' reason='edges'", "spw='17:0~3;123~127' reason='edges'", "spw='23:0~3;126~127' reason='edges'", "mode='summary' name='after'"])
    flagdata(vis='uid___A002_Xc889b6_X5cbc.ms.h_tsyscal.s6_1.tsyscal.tbl', mode='summary')
    flagdata(flagbackup=False, vis='uid___A002_Xc889b6_X5cbc.ms.h_tsyscal.s6_1.tsyscal.tbl', reason='any', mode='list', action='apply', savepars=False, inpfile=["mode='summary' name='before'", "spw='19:94~103' antenna='DA43,DA42,DA45,DA50,DA54,DV02,DV05' reason='sharps'", "mode='summary' name='after'"])
    flagdata(vis='uid___A002_Xc889b6_X5cbc.ms.h_tsyscal.s6_1.tsyscal.tbl', mode='summary')
    #hifa_tsysflag(pipelinemode="automatic")
    hifa_antpos(pipelinemode="automatic")
    hifa_wvrgcalflag(pipelinemode="automatic")
    hif_lowgainflag(pipelinemode="automatic")
    hif_setmodels(pipelinemode="automatic")
    hifa_bandpassflag(pipelinemode="automatic")
    hifa_spwphaseup(pipelinemode="automatic")
    hifa_gfluxscaleflag(pipelinemode="automatic")
    hifa_gfluxscale(pipelinemode="automatic")
    hifa_timegaincal(pipelinemode="automatic")
    hif_applycal(pipelinemode="automatic")
    hifa_imageprecheck(pipelinemode="automatic")
    hif_makeimlist(intent='PHASE,BANDPASS,CHECK')
    hif_makeimages(pipelinemode="automatic")
    hif_checkproductsize(maxcubelimit=40.0, maxproductsize=400.0, maxcubesize=30.0)
    hifa_exportdata(pipelinemode="automatic")
    hif_mstransform(pipelinemode="automatic")
    hifa_flagtargets(pipelinemode="automatic")
    hif_makeimlist(specmode='mfs')
    hif_findcont(pipelinemode="automatic")
    hif_uvcontfit(pipelinemode="automatic")
    hif_uvcontsub(pipelinemode="automatic")
    hif_makeimages(pipelinemode="automatic")
    hif_makeimlist(specmode='cont')
    hif_makeimages(pipelinemode="automatic")
    #hif_makeimlist(pipelinemode="automatic")
    #hif_makeimages(pipelinemode="automatic")
    #hif_makeimlist(specmode='repBW')
    #hif_makeimages(pipelinemode="automatic")
finally:
    h_save()
