from recipes.almahelpers import fixsyscaltimes # SACM/JAO - Fixes
__rethrow_casa_exceptions = True
context = h_init()
context.set_state('ProjectSummary', 'proposal_code', '2017.1.01355.L')
context.set_state('ProjectSummary', 'piname', 'unknown')
context.set_state('ProjectSummary', 'proposal_title', 'unknown')
context.set_state('ProjectStructure', 'ous_part_id', 'X1932261395')
context.set_state('ProjectStructure', 'ous_title', 'Undefined')
context.set_state('ProjectStructure', 'ppr_file', '/mnt/jaosco/data/lcerrigo/Working/TPdata/2017.1.01355.L_2018_05_12T11_12_25.550/SOUS_uid___A001_X1296_X183/GOUS_uid___A001_X1296_X184/MOUS_uid___A001_X1296_X189/working/PPR_uid___A001_X1296_X18a.xml')
context.set_state('ProjectStructure', 'ps_entity_id', 'uid://A001/X1220/Xddd')
context.set_state('ProjectStructure', 'recipe_name', 'hifa_calimage')
context.set_state('ProjectStructure', 'ous_entity_id', 'uid://A001/X1220/Xdd9')
context.set_state('ProjectStructure', 'ousstatus_entity_id', 'uid://A001/X1296/X189')
try:
    hifa_importdata(vis=['../rawdata/uid___A002_Xcccc19_Xb7a6', '../rawdata/uid___A002_Xccde5b_X5258', '../rawdata/uid___A002_Xccde5b_X5ef0', '../rawdata/uid___A002_Xccea8d_X3fee', '../rawdata/uid___A002_Xccea8d_Xeed1', '../rawdata/uid___A002_Xcd07af_X5991', '../rawdata/uid___A002_Xcd1950_X40d9', '../rawdata/uid___A002_Xcd1950_X6006', '../rawdata/uid___A002_Xcd2acd_X5fab', '../rawdata/uid___A002_Xcd3dcc_X21cd'], session=['session_2', 'session_3', 'session_4', 'session_5', 'session_6', 'session_7', 'session_8', 'session_9', 'session_10', 'session_11'])
    fixsyscaltimes(vis = 'uid___A002_Xccea8d_Xeed1.ms')# SACM/JAO - Fixes
    fixsyscaltimes(vis = 'uid___A002_Xccea8d_X3fee.ms')# SACM/JAO - Fixes
    fixsyscaltimes(vis = 'uid___A002_Xccde5b_X5ef0.ms')# SACM/JAO - Fixes
    fixsyscaltimes(vis = 'uid___A002_Xcd07af_X5991.ms')# SACM/JAO - Fixes
    fixsyscaltimes(vis = 'uid___A002_Xcd2acd_X5fab.ms')# SACM/JAO - Fixes
    fixsyscaltimes(vis = 'uid___A002_Xccde5b_X5258.ms')# SACM/JAO - Fixes
    fixsyscaltimes(vis = 'uid___A002_Xcd1950_X6006.ms')# SACM/JAO - Fixes
    fixsyscaltimes(vis = 'uid___A002_Xcd3dcc_X21cd.ms')# SACM/JAO - Fixes
    fixsyscaltimes(vis = 'uid___A002_Xcccc19_Xb7a6.ms')# SACM/JAO - Fixes
    fixsyscaltimes(vis = 'uid___A002_Xcd1950_X40d9.ms')# SACM/JAO - Fixes
    h_save() # SACM/JAO - Finish weblog after fixes
    context = h_init() # SACM/JAO - Restart weblog after fixes
    context.set_state('ProjectSummary', 'proposal_code', '2017.1.01355.L')
    context.set_state('ProjectSummary', 'piname', 'unknown')
    context.set_state('ProjectSummary', 'proposal_title', 'unknown')
    context.set_state('ProjectStructure', 'ous_part_id', 'X1932261395')
    context.set_state('ProjectStructure', 'ous_title', 'Undefined')
    context.set_state('ProjectStructure', 'ppr_file', '/mnt/jaosco/data/lcerrigo/Working/TPdata/2017.1.01355.L_2018_05_12T11_12_25.550/SOUS_uid___A001_X1296_X183/GOUS_uid___A001_X1296_X184/MOUS_uid___A001_X1296_X189/working/PPR_uid___A001_X1296_X18a.xml')
    context.set_state('ProjectStructure', 'ps_entity_id', 'uid://A001/X1220/Xddd')
    context.set_state('ProjectStructure', 'recipe_name', 'hifa_calimage')
    context.set_state('ProjectStructure', 'ous_entity_id', 'uid://A001/X1220/Xdd9')
    context.set_state('ProjectStructure', 'ousstatus_entity_id', 'uid://A001/X1296/X189')
    hifa_importdata(vis=['../rawdata/uid___A002_Xcccc19_Xb7a6', '../rawdata/uid___A002_Xccde5b_X5258', '../rawdata/uid___A002_Xccde5b_X5ef0', '../rawdata/uid___A002_Xccea8d_X3fee', '../rawdata/uid___A002_Xccea8d_Xeed1', '../rawdata/uid___A002_Xcd07af_X5991', '../rawdata/uid___A002_Xcd1950_X40d9', '../rawdata/uid___A002_Xcd1950_X6006', '../rawdata/uid___A002_Xcd2acd_X5fab', '../rawdata/uid___A002_Xcd3dcc_X21cd'], session=['session_2', 'session_3', 'session_4', 'session_5', 'session_6', 'session_7', 'session_8', 'session_9', 'session_10', 'session_11'])
    hifa_flagdata(pipelinemode="automatic")
    hifa_fluxcalflag(pipelinemode="automatic")
    hif_rawflagchans(pipelinemode="automatic")
    hif_refant(pipelinemode="automatic")
    h_tsyscal(pipelinemode="automatic")
    flagdata(vis='uid___A002_Xcccc19_Xb7a6.ms.h_tsyscal.s6_1.tsyscal.tbl',spw='26:297~307',field='W51-IRS2',flagbackup=False)
    flagdata(vis='uid___A002_Xccde5b_X5258.ms.h_tsyscal.s6_3.tsyscal.tbl',spw='26:297~307',field='W51-IRS2',flagbackup=False)
    flagdata(vis='uid___A002_Xccde5b_X5ef0.ms.h_tsyscal.s6_5.tsyscal.tbl',spw='26:297~307',field='W51-IRS2',flagbackup=False)
    flagdata(vis='uid___A002_Xccea8d_X3fee.ms.h_tsyscal.s6_7.tsyscal.tbl',spw='26:297~307',field='W51-IRS2',flagbackup=False)
    flagdata(vis='uid___A002_Xccea8d_Xeed1.ms.h_tsyscal.s6_9.tsyscal.tbl',spw='26:297~307',field='W51-IRS2',flagbackup=False)
    flagdata(vis='uid___A002_Xcd07af_X5991.ms.h_tsyscal.s6_11.tsyscal.tbl',spw='26:297~307',field='W51-IRS2',flagbackup=False)
    flagdata(vis='uid___A002_Xcd1950_X40d9.ms.h_tsyscal.s6_13.tsyscal.tbl',spw='26:297~307',field='W51-IRS2',flagbackup=False)
    flagdata(vis='uid___A002_Xcd1950_X6006.ms.h_tsyscal.s6_15.tsyscal.tbl',spw='26:297~307',field='W51-IRS2',flagbackup=False)
    flagdata(vis='uid___A002_Xcd2acd_X5fab.ms.h_tsyscal.s6_17.tsyscal.tbl',spw='26:297~307',field='W51-IRS2',flagbackup=False)
    flagdata(vis='uid___A002_Xcd3dcc_X21cd.ms.h_tsyscal.s6_19.tsyscal.tbl',spw='26:297~307',field='W51-IRS2',flagbackup=False)
    hifa_tsysflag(pipelinemode="automatic")
    hifa_antpos(pipelinemode="automatic")
    hifa_wvrgcalflag(pipelinemode="automatic")
    hif_lowgainflag(pipelinemode="automatic")
    hif_setmodels(pipelinemode="automatic")
    hifa_bandpassflag(pipelinemode="automatic")
    hifa_spwphaseup(pipelinemode="automatic")
    hifa_gfluxscaleflag(pipelinemode="automatic")
    hifa_gfluxscale(pipelinemode="automatic")
    hifa_timegaincal(pipelinemode="automatic")
    hif_applycal(pipelinemode="automatic")
    hifa_imageprecheck(pipelinemode="automatic")
    hif_makeimlist(intent='PHASE,BANDPASS,CHECK')
    hif_makeimages(pipelinemode="automatic")
    hif_checkproductsize(maxcubelimit=40.0, maxproductsize=400.0, maxcubesize=30.0)
    hifa_exportdata(pipelinemode="automatic")
    hif_mstransform(pipelinemode="automatic")
    hifa_flagtargets(pipelinemode="automatic")
    hif_makeimlist(specmode='mfs')
    hif_findcont(pipelinemode="automatic")
    hif_uvcontfit(pipelinemode="automatic")
    hif_uvcontsub(pipelinemode="automatic")
    hif_makeimages(pipelinemode="automatic")
    hif_makeimlist(specmode='cont')
    hif_makeimages(pipelinemode="automatic")
    hif_makeimlist(pipelinemode="automatic")
    hif_makeimages(pipelinemode="automatic")
    hif_makeimlist(specmode='repBW')
    hif_makeimages(pipelinemode="automatic")
    hifa_exportdata(pipelinemode="automatic")
finally:
    h_save()
